# Generated by Django 5.1.1 on 2024-10-02 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=256, verbose_name='место, в котором необходимо выполнять привычку')),
                ('date_time', models.DateTimeField(verbose_name='время, когда необходимо выполнять привычку')),
                ('habit_to_do', models.CharField(max_length=1024, verbose_name='действие, которое представляет собой привычка')),
                ('frequency', models.IntegerField(default=1, verbose_name='периодичность, в днях')),
                ('award', models.CharField(max_length=1024, verbose_name='награда за успешное выполнение')),
                ('time_to_do', models.TimeField(default=datetime.time(0, 10), verbose_name='время требуемое на выполнение задачи')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичный/непубличный')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
