# Generated by Django 5.1.1 on 2024-10-06 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=256, verbose_name='место, в котором необходимо выполнять привычку')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='дата и время, когда необходимо выполнять привычку')),
                ('habit_to_do', models.CharField(max_length=1024, verbose_name='действие, которое представляет собой привычка')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('frequency', models.IntegerField(default=1, verbose_name='периодичность, в днях')),
                ('award', models.CharField(max_length=1024, verbose_name='награда за успешное выполнение')),
                ('time_to_do', models.PositiveIntegerField(default=120, verbose_name='время требуемое на выполнение задачи, в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичный/непубличный')),
                ('linked_habit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HabitFormation.habit', verbose_name='связанная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
