# Generated by Django 5.1.1 on 2024-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitFormation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_do',
            field=models.IntegerField(default=120, verbose_name='время требуемое на выполнение задачи, в секундах'),
        ),
    ]
